# Generated by Django 5.1.3 on 2024-11-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_union',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='es_personal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='es_superusuario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='esta_activo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si este usuario está activo.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al sitio de administración.', verbose_name='Estado de Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene todos los permisos.', verbose_name='Estado de Superusuario'),
        ),
    ]
